# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: nginx
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/andrei-verdes/argocd-test
#     path: test-app  # Points to the top-level directory
#     targetRevision: HEAD
#     directory:
#       recurse: true
#   destination:
#     server: "https://kubernetes.default.svc"
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true