apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: accounting
  namespace: buy
spec:
  project: development
  source:
    chart: nginx
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.2.5
  destination:
    server: "https://kubernetes.default.svc"
    namespace: buy