apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    chart: helmtest
    repoURL: registry-1.docker.io/andrewv23
    targetRevision: 0.1.3
    helm:
      parameters:
        - name: "environment"
          value: staging
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true