apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    chart: helmtest
    repoURL: andrewv23
    targetRevision: 0.1.0
    helm:
      parameters:
        - name: "environment"
          value: development
  destination:
    server: "https://kubernetes.default.svc"
    namespace: buy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true